'use strict';

const HUB_CHANNEL_ID = process.env.SESSION_HUB_CHANNEL_ID || null;
const ATTENDEES_CHANNEL_ID = process.env.SESSION_LOG_CHANNEL_ID || process.env.SESSION_ATTENDEES_CHANNEL_ID || HUB_CHANNEL_ID;
const HUB_PING_ROLE_ID = process.env.SESSION_HUB_PING_ROLE_ID || null;

module.exports = {
  QUEUE_INTERVIEW_CHANNEL_ID: process.env.QUEUE_INTERVIEW_CHANNEL_ID || process.env.SESSION_INTERVIEW_CHANNEL_ID || HUB_CHANNEL_ID,
  QUEUE_TRAINING_CHANNEL_ID: process.env.QUEUE_TRAINING_CHANNEL_ID || process.env.SESSION_TRAINING_CHANNEL_ID || HUB_CHANNEL_ID,
  QUEUE_MASSSHIFT_CHANNEL_ID: process.env.QUEUE_MASS_SHIFT_CHANNEL_ID || process.env.QUEUE_MASSSHIFT_CHANNEL_ID || process.env.SESSION_MASS_SHIFT_CHANNEL_ID || process.env.SESSION_MASSSHIFT_CHANNEL_ID || HUB_CHANNEL_ID,

  QUEUE_INTERVIEW_ATTENDEES_CHANNEL_ID: process.env.QUEUE_INTERVIEW_ATTENDEES_CHANNEL_ID || ATTENDEES_CHANNEL_ID,
  QUEUE_TRAINING_ATTENDEES_CHANNEL_ID: process.env.QUEUE_TRAINING_ATTENDEES_CHANNEL_ID || ATTENDEES_CHANNEL_ID,
  QUEUE_MASSSHIFT_ATTENDEES_CHANNEL_ID: process.env.QUEUE_MASS_SHIFT_ATTENDEES_CHANNEL_ID || process.env.QUEUE_MASSSHIFT_ATTENDEES_CHANNEL_ID || ATTENDEES_CHANNEL_ID,

  QUEUE_INTERVIEW_PING_ROLE_ID: process.env.QUEUE_INTERVIEW_PING_ROLE_ID || HUB_PING_ROLE_ID,
  QUEUE_TRAINING_PING_ROLE_ID: process.env.QUEUE_TRAINING_PING_ROLE_ID || HUB_PING_ROLE_ID,
  QUEUE_MASSSHIFT_PING_ROLE_ID: process.env.QUEUE_MASS_SHIFT_PING_ROLE_ID || process.env.QUEUE_MASSSHIFT_PING_ROLE_ID || HUB_PING_ROLE_ID,
};
