// src/config/trello.js
require('dotenv').config();

module.exports = {
  TRELLO_KEY: process.env.TRELLO_KEY,
  TRELLO_TOKEN: process.env.TRELLO_TOKEN,
  TRELLO_BOARD_ID: process.env.TRELLO_BOARD_ID,

  TRELLO_LIST_INTERVIEW_ID: process.env.TRELLO_LIST_INTERVIEW_ID,
  TRELLO_LIST_TRAINING_ID: process.env.TRELLO_LIST_TRAINING_ID,
  TRELLO_LIST_MASS_SHIFT_ID: process.env.TRELLO_LIST_MASS_SHIFT_ID,
  TRELLO_LIST_COMPLETED_ID: process.env.TRELLO_LIST_COMPLETED_ID,

  // NEW:
  TRELLO_LIST_IN_PROGRESS_ID: process.env.TRELLO_LIST_IN_PROGRESS_ID,

  TRELLO_LABEL_SCHEDULED_ID: process.env.TRELLO_LABEL_SCHEDULED_ID,
  TRELLO_LABEL_INTERVIEW_ID: process.env.TRELLO_LABEL_INTERVIEW_ID,
  TRELLO_LABEL_TRAINING_ID: process.env.TRELLO_LABEL_TRAINING_ID,
  TRELLO_LABEL_MASS_SHIFT_ID: process.env.TRELLO_LABEL_MASS_SHIFT_ID,
  TRELLO_LABEL_COMPLETED_ID: process.env.TRELLO_LABEL_COMPLETED_ID,
  TRELLO_LABEL_CANCELED_ID: process.env.TRELLO_LABEL_CANCELED_ID,

  // NEW:
  TRELLO_LABEL_IN_PROGRESS_ID: process.env.TRELLO_LABEL_IN_PROGRESS_ID,
};
